### ISSUE TITLE
having some trouble with whale_watch.py ? 

### ISSUE THREAD

**Issue by gilfunk** [LooseLab/bulkvis#23]
Im trying to use this whale_watch.py script to find fused reads. 

the error message is this   :: 
  TypeError: unsupported operand type(s) for -: 'str' and 'str'

I think this where the error is coming from ::   
File "whale_watch.py", line 36, in fuse_reads
    ss['diff'] = ss['start_time'].shift(-1) - (ss['start_time'] + ss['duration']) 

 Thanks for any assistance!  
  This might be something basic on my end .. in which case apologies. 

Here is the whole error message i am getting   :: 

Traceback (most recent call last):
  File "whale_watch.py", line 289, in <module>
    main()
  File "whale_watch.py", line 11, in main
    fused_df, ss, fused_read_ids = fuse_reads(args.summary, args.paf, args.distance, args.top, args.alt, args.debug)
  File "whale_watch.py", line 36, in fuse_reads
    ss['diff'] = ss['start_time'].shift(-1) - (ss['start_time'] + ss['duration'])
  File "/usr/lib/anaconda3/lib/python3.6/site-packages/pandas/core/ops.py", line 1069, in wrapper
    result = safe_na_op(lvalues, rvalues)
  File "/usr/lib/anaconda3/lib/python3.6/site-packages/pandas/core/ops.py", line 1037, in safe_na_op
    lambda x: op(x, rvalues))
  File "pandas/_libs/algos_common_helper.pxi", line 1212, in pandas._libs.algos.arrmap_object
  File "/usr/lib/anaconda3/lib/python3.6/site-packages/pandas/core/ops.py", line 1037, in <lambda>
    lambda x: op(x, rvalues))
TypeError: unsupported operand type(s) for -: 'str' and 'str'

**Comment by alexomics** [comment]
This error message suggests that the format of your sequencing summary file is not as expected. If could share the input file(s) that are causing this error I can take a closer look.

**Comment by gilfunk** [comment]
Thank you !! you are totally correct ! 
 i found the formatting error (extra header lines from concatenating ) 
   took them out and it now works beautifully 
   <3 <3 <3
