### ISSUE TITLE
h5py

### ISSUE THREAD

**Issue by malkadi89** [LooseLab/bulkvis#28]
I got this message:
KeyError: "Unable to open object (object 'IntermediateData' doesn't exist)"
full details:
command is:
$ bulkvis>python utils\set_config.py -b ..\test\FAK47977_78c30614cc65b2b97c46e55b3057dc404e30b4db_0.fast5 -i ..\test -m ..\test -e ..\test -c config.ini
Error message
Traceback (most recent call last):
  File "utils\set_config.py", line 121, in <module>
    main()
  File "utils\set_config.py", line 74, in main
    int_data_path = bulkfile["IntermediateData"]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\moham\bulkvis\lib\site-packages\h5py\_hl\group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'IntermediateData' doesn't exist)"

seem a problem with h5py. I tried it on 3 machines (one Windows and two Linux) and I got the same problem. Other tools that use h5py work fine. How can I fix this problem?

Regards,

**Comment by alexomics** [comment]
Hi, 

The file that you are passing to the script `set_config.py` is a read FAST5 file, this doesn't have the extra contextual data that drives bulkvis. You will need to use a bulk FAST5 file, which will be in the top level of your MinKNOW data folder and have a name like: `GXB00420_20190822_110836_FAL00009_gridion_sequencing_run_RUN_NAME.fast5`.

To collect a bulk FAST5 file, on the output tab select "Additional options", turn "Bulk file" to on, unselect "Events" and select "Raw"; as below.

![image](https://user-images.githubusercontent.com/30386655/63493456-8c16b800-c4b3-11e9-82eb-265ce4b03cd2.png)


Alex
