### ISSUE TITLE
Bokeh Application Handler Error

### ISSUE THREAD

**Issue by kuhnem** [LooseLab/bulkvis#39]
Hi there,

I am trying to get this to work on a Windows 10 machine. The error below persists using both Python 3.5 and Python 3.7. The Bokeh window opened in my browser is entirely blank. I'd be happy about any suggestions. Thanks!

===
(py37env) D:\Tools\Bioinformatics>bokeh serve --show bulkvis

2020-05-05 13:42:40,750 Starting Bokeh server version 0.12.15 (running on Tornado 5.0.1)
2020-05-05 13:42:40,750 Bokeh app running at: http://localhost:5006/bulkvis
2020-05-05 13:42:40,750 Starting Bokeh server with process id: 11364
2020-05-05 13:42:41,137 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x00000263371E0EF0>: 'plot_opts'
File "configparser.py", line 958, in __getitem__:
raise KeyError(key) Traceback (most recent call last):
  File "d:\tools\bioinformatics\py37env\lib\site-packages\bokeh\application\handlers\code_runner.py", line 173, in run
    exec(self._code, module.__dict__)
  File "D:\Tools\Bioinformatics\bulkvis\main.py", line 19, in <module>
    cfg_po = config['plot_opts']
  File "c:\python37\lib\configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'plot_opts'

2020-05-05 13:42:41,153 200 GET /bulkvis (::1) 124.97ms
2020-05-05 13:42:41,388 101 GET /bulkvis/ws?bokeh-protocol-version=1.0&bokeh-session-id=vy5wnHDyUkL8mwnRHRzsDJXbl9HUHX9wwrHROmOe7DOK (::1) 0.00ms
2020-05-05 13:42:41,388 WebSocket connection opened
2020-05-05 13:42:41,388 ServerConnection created

===============================

Here's my list of packages installed.

(py37env) D:\Tools\Bioinformatics>pip freeze
bokeh==0.12.15
h5py==2.8.0
Jinja2==2.10
MarkupSafe==1.0
numpy==1.14.6
packaging==20.3
pandas==0.23.0
Pillow==5.1.0
pyparsing==2.4.7
python-dateutil==2.7.2
pytz==2018.3
PyYAML==3.12
selenium==3.11.0
six==1.11.0
tornado==5.0.1
tqdm==4.20.0

**Comment by alexomics** [comment]
Have you set up a config file? See [`config.md`](https://github.com/LooseLab/bulkvis/blob/master/config.md)

**Comment by kuhnem** [comment]
Thanks for the quick response, I did in fact forget that. Has Oxford Nanopore changed its data structure? I have fast5_pass and fast5_fail folders as well as fastq_pass and fastq_fail folders, both containing several *.fast5 and *.fastq files. I don't seem to have an overall bulkfile. So when I try to setup the config file, I get the error:

KeyError: "Unable to open object (object 'IntermediateData' doesn't exist)"

**Comment by alexomics** [comment]
The bulk FAST5 file is different from the ones contained in the pass/fail folders. It is a complete record of the sequencing experiment and usually gigabytes in size. The option to collect a bulk FAST5 file is in the "Advanced user options" section of the "Output" tab:

![image](https://user-images.githubusercontent.com/30386655/81101594-49442580-8f06-11ea-9db2-69646ae9bc55.png)

This must be turned on when you setup the experiment.

**Comment by kuhnem** [comment]
Got it, thanks a lot!
