### ISSUE TITLE
No bulk fast5 shown in  web browser

### ISSUE THREAD

**Issue by sherkinglee** [LooseLab/bulkvis#42]
Hi, 
I successfully downloaded bulkvis and when I want to start with command as following nothing shown on the web page:
$ bokeh serve --show bulkvis-master

![image](https://user-images.githubusercontent.com/33414410/101761884-a7c62780-3b17-11eb-995d-11f5f03414fc.png)

The config.init is described as :
[data]
dir = /Share2/home/lifj/Projects/12.Nanopore/Zhiyuan-20201104/Data/20201102_XRNAX_test_1_RNA002_85ng/no_sample/20201102_1331_MN32106_FAL
58344_8d29359e/fast5_pass/
out = /Share2/home/lifj/Projects/12.Nanopore/Zhiyuan-20201104/01.base_calling/fastq/
map = /Share2/home/lifj/Projects/12.Nanopore/Zhiyuan-20201104/06.minimap2/withSecondaryAlignment/sam/
[plot_opts]
wdg_width = 300
plot_width = 1600
plot_height = 1000
y_min = 0
y_max = 2200
label_height = 800
upper_cut_off = 2200
lower_cut_off = -1000
;recommended that this is kept as 'canvas' opts: ['canvas', 'svg', 'webgl']
 output_backend = canvas
[labels]
 adapter = True
 mux_uncertain = True
 strand1 = False
 user1 = True
 event = False
 user2 = False
 multiple = False
 unclassed = False
 pore = True
 strand = True
 transition = True
 unavailable = False
 zero = False
 saturated = False
 unblocking = True
 good_single = False
 below = False
 above = True
 inrange = False
 unclassified = False
 unclassified_following_reset = False
 pending_manual_reset = False
 pending_mux_change = False]

I have no idea what is going on and totally be stucked. Could you help me to solve this problem?

**Comment by alexomics** [comment]
From your input directory (`dir`) it looks like you are passing in a folder of read FAST5 files. bulkvis requires a bulk FAST5 file to run

**Comment by sherkinglee** [comment]
Oh...I see!  Thanks for your kind reply. One more question, is it the _out_ that represents the folder of read fastq file and _map_ represnts the folder of sam/bam file which were generated by minimap2?

**Comment by sherkinglee** [comment]
Hi, 
I tried use a bulk fast5 as an input and run _bokeh serve --show bulkvis-master/_ but got an error like this:
2020-12-14 14:27:00,103 Starting Bokeh server version 0.12.15 (running on Tornado 5.0.1)
2020-12-14 14:27:00,232 Bokeh app running at: http://localhost:5006/bulkvis-master
2020-12-14 14:27:00,232 Starting Bokeh server with process id: 70626
/usr/bin/xdg-open: line 402: htmlview: command not found
2020-12-14 14:27:12,261 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x7feae347c438>: Can't read data (can't open directory: /usr/local/hdf5/lib/plugin)
File "_proxy.pyx", line 112, in h5py._proxy.dset_rw:
 Traceback (most recent call last):
  File "/Share2/home/lifj/Software/anaconda3/envs/bulkvis/lib/python3.6/site-packages/bokeh/application/handlers/code_runner.py", line 173, in run
    exec(self._code, module.__dict__)
  File "/Share2/home/lifj/Software/bulkvis-master/main.py", line 820, in <module>
    try_path[channel]["Signal"][0]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Share2/home/lifj/Software/anaconda3/envs/bulkvis/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 787, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 192, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 112, in h5py._proxy.dset_rw
OSError: Can't read data (can't open directory: /usr/local/hdf5/lib/plugin)

2020-12-14 14:27:12,743 200 GET /bulkvis-master (::1) 3270.73ms
2020-12-14 14:27:12,808 200 GET /static/css/bokeh-widgets.min.css?v=e2198c0464ced10f820b120714112595 (::1) 12.68ms
2020-12-14 14:27:12,808 200 GET /static/css/bokeh-tables.min.css?v=89abce161b192f3f74677f425212bd62 (::1) 2.74ms
2020-12-14 14:27:12,809 200 GET /static/css/bokeh.min.css?v=f7fe43f4980a82921415acbd60d5fd66 (::1) 2.10ms
2020-12-14 14:27:13,829 101 GET /bulkvis-master/ws?bokeh-protocol-version=1.0&bokeh-session-id=gdMrVGuNJO4853eMS3KIdg9kW2877gyhE2kjuJQwKGCB (::1) 22.32ms
2020-12-14 14:27:13,830 WebSocket connection opened
2020-12-14 14:27:13,830 ServerConnection created.

And there is nothing shown on the web page. I tried to uninstall h5py using "pip uninstall h5py" and re-install it "pip install h5py", the error is still there. have you encounter this error before?  The config.ini is as following:

[data]
dir = /Share2/home/lifj/Projects/12.Nanopore/Zhiyuan-20201104/Data
out = /Share2/home/lifj/Projects/12.Nanopore/Zhiyuan-20201104/Data/20201102_XRNAX_test_1_RNA002_85ng/no_sample/20201102_1331_MN32106_FAL58344_8d29359e/all_basecalling.fastq
map = /Share2/home/lifj/Projects/12.Nanopore/Zhiyuan-20201104/10.minimap2-no-filtering
[plot_opts]
wdg_width = 300
plot_width = 1600
plot_height = 1000
y_min = 0
y_max = 2200
label_height = 800
upper_cut_off = 2200
lower_cut_off = -1000
;recommended that this is kept as 'canvas' opts: ['canvas', 'svg', 'webgl']
 output_backend = canvas
[labels]
 adapter = True
 mux_uncertain = True
 strand1 = False
 user1 = True
 event = False
 user2 = False
 multiple = False
 unclassed = False
 pore = True
 strand = True
 transition = True
 unavailable = False
 zero = False
 saturated = False
 unblocking = True
 good_single = False
 below = False
 above = True
 inrange = False
 unclassified = False
 unclassified_following_reset = False
 pending_manual_reset = False
 pending_mux_change = False]
 And the bulk fast5 file "LAPTOP-FU58ST4O_20201102_1332_FAL58344_MN32106_sequencing_run_no_sample_fe61dd91.fast5" is in /Share2/home/lifj/Projects/12.Nanopore/Zhiyuan-20201104/Data.

Thanks a lot.

Sherking
