### ISSUE TITLE
Bulkvis installed with conda on mac

### ISSUE THREAD

**Issue by HAHasani** [LooseLab/bulkvis#53]
Hi,
after installing bulkvis as described [here](https://github.com/LooseLab/bulkvis); I tried to generate a fuse file as follows:
`bulkvis fuse -p minimap/test_0.25.paf.gz -s rawseq/sequencing_summary.txt.gz -o bulkvis/test_025`
However, the error bellow is triggered, could you please help?

thank you

> Traceback (most recent call last):
  File "/Users/HAHasani/miniconda3/envs/bulkvis/lib/python3.7/site-packages/bulkvis/core.py", line 31, in concat_files_to_df
    df_list.append(pd.read_csv(filepath_or_buffer=f, **kwargs))
  File "/Users/HAHasani/miniconda3/envs/bulkvis/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/HAHasani/miniconda3/envs/bulkvis/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/Users/HAHasani/miniconda3/envs/bulkvis/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/Users/HAHasani/miniconda3/envs/bulkvis/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/HAHasani/miniconda3/envs/bulkvis/lib/python3.7/site-packages/pandas/io/parsers.py", line 1937, in __init__
    _validate_usecols_names(usecols, self.orig_names)
  File "/Users/HAHasani/miniconda3/envs/bulkvis/lib/python3.7/site-packages/pandas/io/parsers.py", line 1233, in _validate_usecols_names
    "Usecols do not match columns, "
ValueError: Usecols do not match columns, columns expected but not found: ['filename']

**Comment by alexomics** [comment]
I've just pushed a fix for that error. You will need to re-install bulkvis as described in the README and it should work. Please let me know.

**Comment by HAHasani** [comment]
Thank again; it is running now, but the process is killed after 2 minutes without any error. The memory consumption was not big so I don't know where to take it from there?

**Comment by alexomics** [comment]
Do you have an error message? or does it just say `Killed` ?

**Comment by HAHasani** [comment]
Just `zsh: killed`. I didn't see anything fishy during these 2 minutes & there is no verbose mode or log to know where exactly it stopped.
